### PR TITLE
update links in android/index.md

### PR DESCRIPTION
**Pull request by asashour**
BTW: I couldn't find `opencv_cheatsheet.pdf` for latest version.

### CODE REVIEW

**Comment by mshabunin** [comment]
@asashour , we've moved to the new site engine, these repository is not used anymore.

@spmallick , please take a look, can we update these links?

**Comment by spmallick** [comment]
Thanks. We will update it by tomorrow.

**Comment by asashour** [comment]
Thanks all, is there a way to communicate suggestions to the "new site engine"?

**Comment by mshabunin** [comment]
@asashour , yes, you can do it via issue tracker for this repository: https://github.com/opencv-infrastructure/opencv.org/issues

**Pull request closed without merging**
