### PR TITLE
Update releases.yml

### PR DESCRIPTION
**Pull request by sturkmen72**
release date is corrected.
a dead link is removed.
most popular links moved on top.

### CODE REVIEW

**Comment by alalek** [comment]
BTW, Current view of [the GitHub traffic page](https://github.com/opencv/opencv/graphs/traffic) (for last 1 or 2 weeks):
github_opencv_traffic_20171230

**Comment by mshabunin** [comment]
Thank you! I'll update the site tomorrow.

**Comment by sturkmen72** [comment]
https://github.com/opencv/opencv/wiki needs to be updated

latest releases: 3.3.1 and 2.4.13.4

**Comment by mshabunin** [comment]
@sturkmen72 , fixed. Thank you!

**Pull request merged**
